name: Java + Prettier Check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  lint-java-with-prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies (Prettier + Java plugin)
        run: |
          yarn init -y
          yarn add --dev prettier prettier-plugin-java

      - name: Run Prettier check
        run: |
          yarn prettier --plugin ./node_modules/prettier-plugin-java/dist/index.js --debug-check -c "sonar-scanner-engine/src/main/java/org/sonar/*.java"